# Generated by Django 3.1.2 on 2020-11-15 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 22, 5, 25, 115764)),
        ),
    ]
