# Generated by Django 3.1.2 on 2020-11-15 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201115_2205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        )
    ]
