# Generated by Django 3.1.2 on 2020-11-12 21:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_chat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='Messages',
        ),
    ]
