# Generated by Django 3.1.2 on 2020-11-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtest', '0005_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='messages',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
