# Generated by Django 3.1.2 on 2020-11-12 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtest', '0006_user_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='messages',
        ),
    ]
